### ISSUE TITLE
Medical dataset

### ISSUE THREAD

**Issue by gabrer** [taolei87/rcnn#11]
Congratulation for your results! I really enjoyed your method :)

I wonder if somehow it would be possible to try rcnn on the medical dataset? Shall I ask some to get the data?

Thank you!

**Comment by taoleicn** [comment]
Hi,
I don't think we are allowed to share that data due to privacy restrictions. 
You could perhaps ask the [current team](http://learningtocure.csail.mit.edu/team) members.

Best,
Tao

**Comment by gabrer** [comment]
Hi Tao,
 
thank you for your help!
I will get in touch with them soon.

Best,
Gabriele
