### ISSUE TITLE
Producing Rationales 

### ISSUE THREAD

**Issue by NoahMarconi** [taolei87/rcnn#14]
Looking through the code I don't see where you're producing the text files contained in the example_rationales directory.

Can you point me toward how those files are produced?

**Comment by taolei87** [comment]
Hi @NoahMarconi 

Here is the code: https://github.com/taolei87/rcnn/blob/master/code/rationale/rationale.py#L548-L579
https://github.com/taolei87/rcnn/blob/master/code/rationale/rationale_dependent.py#L575-L600

It dumps the sampled z and a bunch of other things to a json file. and I pull out the rationales from it.

**Comment by NoahMarconi** [comment]
Thanks, it looks like your main function requires a `rationale` file to exist before dispatching the `dump_rationales` method.

https://github.com/taolei87/rcnn/blob/master/code/rationale/rationale.py#L335:L342

and 

https://github.com/taolei87/rcnn/blob/master/code/rationale/rationale.py#L468:L470

I think I'm good now, after initializing  `get_loss_and_pred` and  `sample_generator` in the main function I can create new rationales without relying on loading pre-existing ones.

**Comment by taolei87** [comment]
yeah. `sample_generator` is the one to use if you just need to get / visualize the selected words.
