### ISSUE TITLE
Why the condition in LSTM/GRU model is x.ndim > 1 but 2?

### ISSUE THREAD

**Issue by Dr-Corgi** [taolei87/rcnn#8]
Hi Taolei,
First of all, thank you for the awesome code. It's really helpful.
However when I tried to use it I was confused about the condition statement in LSTM and GRU model.
In the forward_all() function, the input 'x' is a (n x d) matrix or a (batch x n x d) tensor, so x.ndim is always equal to/larger than 2, isn't it?
On the other hand, when x.ndim == 1, it seems that it's impossible for forward_all() function to scan forward() function, if n_in != 1.

I'm not sure if I have misunderstood the model.
In my opinion, x.ndim is 2 when x is a matrix, and 3 when x is a tensor. So I wonder if the condition statement in these two models should be 'x.ndim > 2', does it? 

I'm not so good at English and I hope I had described it clearly.
Thank you.

**Comment by taolei87** [comment]
Hi @RuiZhang1993 

You are right. That's a typo. In fact, I didn't test the cases when x is a matrix for quite a long time. I always make x batch_n_d during training and test..

**Comment by Dr-Corgi** [comment]
Thank you @taolei87 

There's another issue.
I tried to send an (128_20_50) tensor as input of LSTM to execute the forward_all() function, and it failed. It raise a "ValueError: Shape mismatch: x has 0 rows but z has 20 rows" Error.
But when I used a GRU instead and it worked.
Both the LSTM and the GRU are set as n_in ==50,  n_out == 50

I couldn't understand why

**Comment by taolei87** [comment]
@RuiZhang1993  it is hard to tell the problem without seeing the code. for example, what is z? what are the computations?

One difference between GRU and LSTM is that, LSTM has one more internal state c_i, and you could choose whether to output c_i in forward_all() by setting return_c to True or False. As an outcome, the returned tensor could be len*batch*(n_out*2)  or len*batch*n_out.

You could also see the language model code as an example of using LSTM:
https://github.com/taolei87/rcnn/blob/master/code/language_model/lstm_bptt.py

**Comment by Dr-Corgi** [comment]
Well...Let me show a simple example.

When I tried to execute the code below:

`
from nn.basic import GRU, LSTM
import numpy
import theano.tensor as T
import theano

x_ = T.dtensor3()
lstm_model = LSTM(n_in=50, n_out=50)
outp = lstm_model.forward_all(x_)
test = theano.function(inputs=[x_], outputs=outp)

random_tensor = numpy.random.random((20,128,50))
test(random_tensor)
`

The error information come up as below:

`
Traceback (most recent call last):
  File "/Users/Muenn/PycharmProjects/tiny_lstm_sentimentscore/example.py", line 12, in <module>
    test(random_tensor)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/Library/Python/2.7/site-packages/theano/scan_module/scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Library/Python/2.7/site-packages/theano/scan_module/scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/Users/Muenn/.theano/compiledir_Darwin-15.4.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4316)
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/Users/Muenn/.theano/compiledir_Darwin-15.4.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4193)
ValueError: Shape mismatch: x has 78 rows but z has 128 rows
Apply node that caused the error: Gemm{inplace}(Dot22.0, TensorConstant{1.0}, Subtensor{int64::}.0, <TensorType(float64, matrix)>, TensorConstant{1.0})
Toposort index: 8
Inputs types: [TensorType(float64, matrix), TensorType(float64, scalar), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, scalar)]
Inputs shapes: [(128, 50), (), (78, 100), (50, 50), ()]
Inputs strides: [(400, 8), (), (800, 8), (400, 8), ()]
Inputs values: ['not shown', array(1.0), 'not shown', 'not shown', array(1.0)]
Outputs clients: [[Elemwise{Composite{((scalar_sigmoid((i0 + i1)) * i2) + (scalar_sigmoid((i3 + i4)) * tanh((i5 + i6))))}}[(0, 1)](<TensorType(float64, row)>, Gemm{inplace}.0, Subtensor{:int64:}.0, <TensorType(float64, row)>, Gemm{inplace}.0, <TensorType(float64, row)>, Gemm{inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{maximum,no_inplace}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{int64::}.0, Subtensor{:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{int64::}.0, Subtensor{:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{int64::}.0, Subtensor{:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{int64::}.0, Subtensor{:int64:}.0)
Toposort index: 39
Inputs types: [TensorType(int64, scalar), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, row), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, row), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, row), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, row), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(), (20, 128, 50), (20, 128, 100), (1, 50), (50, 50), (50, 50), (1, 50), (50, 50), (50, 50), (1, 50), (50, 50), (50, 50), (1, 50), (50, 50), (50, 50)]
Inputs strides: [(), (51200, 400, 8), (102400, 800, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8), (400, 8)]
Inputs values: [array(20), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Subtensor{int64:int64:int8, ::, int64::}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1}, Constant{50})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
`

However if I use "GRU" instead of "LSTM", it works.

**Comment by taolei87** [comment]
@RuiZhang1993  the example code works fine for me.

I guess you modified the code and changed the condition:
`if hc.ndim > 1` to `if hc.ndim > 2` in the [foward()](https://github.com/taolei87/rcnn/blob/master/code/nn/basic.py#L374) method, which is wrong.

In the forward() method, the x and hc are either vector or matrix, so the ndim should be 1 or 2.

**Comment by Dr-Corgi** [comment]
Oh, Yes you are right!!
That was my fault.
Thank you very much!

**Comment by taolei87** [comment]
you are welcome :).
